### PR TITLE
Fix broken Field propagation

### PR DESCRIPTION
**Pull request by fourpixels**
fixes: https://github.com/k-next/ui/issues/83

### CODE REVIEW

**Comment by fourpixels** [comment]
IMPORTANT TODO: this fix will fix the text field input, but because the mixin was used in a lot of places, we need to check if they depend on `value` being an actual string, rather than being an `event`. We can always have a check for the type of the parameter and if it's event - use `event.target.value`, otherwise just use the value.. But I would rather have different mixins for those.

**Comment by distantnative** [comment]
This seems to fix the concrete issue but then e.g. email field is throwing errors. As you pointed out (and @bastianallgeier mentioned in #85), this is caused by using a mixin for input and fields. I will try to separate it into two mixins and see if we can solve it this way

**Comment by fourpixels** [comment]
I would go with specific mixins for "updateProperty" or "changedUserInput" so it's clear what's going on.  Also I would use spreading so mixins are not inherited/nested as these makes it harder to maintain. We could have specific place for mixins so they do specific functional stuff rather than work fork particular field. Sounds good?

**Comment by distantnative** [comment]
I'm currently doing some cleaning up. Let me finish that and afterwards we can have a look at how to structure mixins, sounds good?

**Comment by distantnative** [comment]
I included this fix in my recent commit which fixes all the side problems as well. If you want, you could now take a closer look at the mixins and maybe also related to #85 and see if you can improve the structure & handling.

**Pull request closed without merging**
